### ISSUE TITLE
Model creation and modification race condition

### ISSUE THREAD

**Issue by headlessme** [nilbus/Backbone.dualStorage#151]
If a model is modified several times in quick succession, before a response from the server is received this leads to duplicate models created in the local storage. This seems to be because the Backbone generated `cid` is ignored and instead a copy of the model is created in `modelUpdatedWithResponse` along with it's own GUID that's used in local storage.

What is the purpose of creating a copy of the model when an existing one is available and could be updated instead?

**Comment by nilbus** [comment]
Although we no longer use `clone()` because of #75, the commit message on e4f1ba8700b368e9dddc88af5b086814d45fc1ba explains the rationale behind not passing the original model to `localsync`.

Given this incorrect behavior you're seeing, maybe there is a better approach. I would consider any alternatives you come up with.
