### ISSUE TITLE
Invalid JSON saved to localStorage after going offline and saving models

### ISSUE THREAD

**Issue by AntSwift** [nilbus/Backbone.dualStorage#92]
I'm testing some scenarios with an existing backbone application to enable local failover.

I've dropped the library straight into the project and all seems well when the remote endpoint is available (i.e models and collections are appearing in the local storage).

After the endpoint is turned off however is get this error in the console:
```
Uncaught SyntaxError: Unexpected token ,
```

After doing some digging the error is raised by the statement:
```coffeescript
_results.push(JSON.parse(localStorage.getItem(this.name + this.sep + id)));
```

This is located on line 187 in the `Store.prototype.findAll` function. It appears to be caused by the JSON being appended with an extra comma and number (e.g. `{…}, 2`).

I've traced through the code and dualStorage doesn't appear to be setting data in this way, could it be Chrome causing the problem or my app?

Ant

**Comment by nilbus** [comment]
This isn't happening in most situations. This could be due to a key collision between a record key and a store name combination. Eg:

1. A record with id '1' is stored in a collection named '1', with key '11' (storeName: 1, id: 1). The comma-separated index for collection 1 is created with one item: '1'. localstorage contains `{1: '1', 11: '{id: 1}'}`. 
2. A record with id '2' is stored in a collection named '11', with key '112' (storeName: 11, id: 2). The comma-separated index for collection 11 is loaded (currently contains `{id: 1}` because of the collision from step 1). Id '2' is appended to the list, so collection 11's index becomes `{id: 1}, 2`. localstorage contains `{1: '1', 11: '{id: 1}, 2'}, 112: '{id: 2}'}`

@AntSwift Do you think this could have been your scenario?

**Comment by nilbus** [comment]
If this is the problem, I think it could be solved by adding a separator character between the keys and values. I'm guessing this was removed to save a character of localstorage space for each record, which can be significant. I see this in the source, and maybe @lucian1900 can confirm the rationale.

```coffeescript
  sep: '' # previously '-'
```

**Comment by nilbus** [comment]
I was able to reproduce the above scenario with this code:

```javascript
c1 = new Backbone.Collection();
c1.storeName = '1';
c1.create({id: 1});
c11=new Backbone.Collection();
c11.storeName='11';
c11.create({id: 2});
c1.fetch({remote: false});
```

To fix
---

If this situation applies to you, you can resolve the issue in either of these ways:
* Configure a separator character to separate the store name from the IDs.
```coffeescript
window.Store.prototype.sep = '-'
```
* Rename your stores using `storeName` so that IDs can't possibly be ambiguous when adjacent to the storeName.

FYI, neither of these is backward compatible with existing localstorage data, but I can't think of a method that would be.
